.gitignore
CONTRIBUTING.md

[DOC] Add contributing.md

---

.github/workflows/hugo-deploy.yml
CONTRIBUTING.md
config/_default/menus.toml
content/home/hero.md
content/home/host.md
content/home/schedule.md
content/home/what-is-bh.md
data/locations.yaml
layouts/events/single.html
layouts/partials/li_compact.html
layouts/partials/li_compact_project.html
layouts/partials/li_list.html
layouts/partials/portfolio_li_card.html
layouts/partials/site_head.html
layouts/partials/widget_page.html
layouts/partials/widgets/faq.html
layouts/partials/widgets/jitsi.html
layouts/partials/widgets/map.html
layouts/partials/widgets/people.html
layouts/partials/widgets/project_portfolio.html
layouts/section/events.html
static/admin/config.yml

Because if there is something that annoys me more than vertical scrolling to read HTML code, it is horizontal scrolling to read HTML code.
The only "actual" change is preparing "placeholders" for the brainhack Donostia and Nordic events on the map

Refactoring: mostly code cleaning

---

content/events/_index.md

Point event hosting application link to 2021 form.

ENH: Point event hosting application link to 2021 form

---

issues_to_pages.py

Refactor issues to pages script with a focus on the possibility to be
able to re-use methods, and make eventual changes be more localized.

ENH: Refactor issues to pages script

---

.github/labeler.yml
.github/workflows/labeler.yml

This fixes the labeller and is the last piece to get our automated "issue to project page" workflow going:
- based on the amazing work from @SamGuay from last year
- polished even further and troubleshooted by the awesome @jhlegarreta

[ENH] set up labeller

---

layouts/partials/widgets/people.html

[FIX] reactivate uisng githjub avatar on team page when none is provided

---

.github/ISSUE_TEMPLATE/project-submission-template.yml
content/home/hero.md
content/home/host.md
content/projects/guidelines.md
issues_to_pages.py
layouts/partials/widgets/project_portfolio.html

fixes #23 
- move a lot of the content from the project page directly into the header of the project submission form
- change trigger to parse issue into page: the trigger is now `status:web_ready` (FYI @jhlegarreta)

[ENH] update project page

---

issues_to_pages.py

Fix issue form regexes in issue to pages script to extract only the
relevant parts of the corresponding sections.

ENH: Fix issue form regexes in issue to pages script

---

content/events/donostia/index.md
content/faq/faq.md
layouts/partials/widgets/faq.html

[FIX] Donostia is back and the camouflaged headers is gone

---

.github/workflows/issue-to-page.yml
requirements.txt

- ENH: Put together requirements file
- ENH: Print Python package information in workflow

ENH: Put together requirements file

---

scripts/issues_to_pages.py

Fix regex patterns.
Fixes #78.

BUG: Fix regex patterns

---

.github/ISSUE_TEMPLATE/project-submission-template.yml
content/events/avoca/index.md
content/events/marburg/index.md
content/events/taipei/index.md
content/events/zagreb/bhg_zagreb_2021_calendar.csv
data/locations.yaml

[EHN] Add and update events

---

scripts/issues_to_pages.py

Refactor regex parts to methods in the issue to pages script.
Improves the encapsulation.

ENH: Refactor regex parts to methods 

---

.github/workflows/issue-to-page.yml

- BUG: Fix issues to pages script URL argument in workflow
- ENH: Print URL and destination script argument values

BUG: Fix url argument in issue to page workflow

---

.github/workflows/test_package.yml
CONTRIBUTING.md
README.md
requirements_dev.txt
scripts/data/issue_data.json
scripts/tests/test_issues_to_pages.py
scripts/tests/test_transform_issues_to_pages.py
scripts/transform_issues_to_pages.py

Add tests to issues to pages module and script:
Make the `scripts` module be a Python package in order to be able to
import the module.
Add testing data.
Add the necessary packages for testing in a separate requirements file.
Add the test workflow badge to the `README` file.

ENH: Add tests to issues to pages module/script

---

content/events/australasia/index.md
content/events/avoca/index.md
content/events/boston/index.md
content/events/donostia/index.md
content/events/geneva/index.md
content/events/marburg/index.md
content/events/marseille/index.md
content/events/metaverse/index.md
content/events/montreal/index.md
content/events/nordic/index.md
content/events/nyc/index.md
content/events/taipei/index.md
content/events/toronto/index.md
content/events/ucla/index.md
content/events/uva/index.md
content/events/western/index.md
content/events/zagreb/index.md
content/events/zurich/index.md
data/locations.yaml

closes #89 
closes #94 
closes #95

[ENH / FIX] update event dates and hybrid/IRL/virtual status

---

README.md

Remove non-existing workflow badge from `README`.

DOC: Remove non-existing workflow badge

---

requirements.txt

[INFRA] update requirements.txt

---

.pre-commit-config.yaml

as this leads to too much noise in the automated PRs

[INFRA] remove trailing white space rule from precommit 

---

.pre-commit-config.yaml

as this too leads to too much noise in the automated PRs

[INFRA] removing end of line rule from precommit 

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/project-submission-template.yml

- ENH: Remove unrelated issue template
- DOC: Remove misleading project template field comment
- DOC: Improve project submission template instruction wording

ENH: Cleanup issue templates
